services:
  mariadb_datos:
    image: mariadb:latest
    container_name: mariadb_datos
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - ../../.env

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_visualizacion
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - mariadb_datos
    env_file:
      - ../../.env

volumes:
  grafana_data: